import React, { useState, useEffect, useRef } from 'react';
import { Activity, Terminal, Shield, Zap, RefreshCw, Server, Database, Mail, Search } from 'lucide-react';

const API_BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:3000';

const CommandCenter = () => {
    // ... rest of component
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
    // ...
                    <div className="flex items-center gap-2 text-green-500">
                        <Terminal size={18} />
                        <span className="text-sm font-bold tracking-widest">&gt;/ BRAIN_ACTIVITY_LOG</span>
                    </div>
                    <div className="flex gap-2">
                        <div className="w-3 h-3 rounded-full bg-red-500/20 border border-red-500"></div>
                        <div className="w-3 h-3 rounded-full bg-yellow-500/20 border border-yellow-500"></div>
                        <div className="w-3 h-3 rounded-full bg-green-500/20 border border-green-500"></div>
                    </div>
                </div >

    <div className="flex-1 overflow-y-auto space-y-3 pr-2 scrollbar-thin scrollbar-thumb-gray-800 scrollbar-track-transparent" ref={scrollRef}>
        {activities.length === 0 ? (
            <div className="text-gray-600 italic text-center mt-10">Initializing neural interface...</div>
        ) : (
            activities.map((act) => (
                <div key={act.id} className={`p-3 rounded border-l-2 text-xs md:text-sm font-mono transition-all hover:bg-white/5 ${getActivityColor(act.type, act.severity)}`}>
                    <div className="flex justify-between items-start mb-1 opacity-70">
                        <span className="uppercase font-bold flex items-center gap-2">
                            {act.type}
                        </span>
                        <span>{new Date(act.created_at).toLocaleTimeString()}</span>
                    </div>
                    <div className="font-bold mb-1">{act.title}</div>
                    <div className="opacity-80 break-words">{act.description}</div>
                    {act.metadata && Object.keys(act.metadata).length > 0 && (
                        <div className="mt-2 text-[10px] text-gray-500 bg-black/30 p-2 rounded overflow-x-auto">
                            {JSON.stringify(act.metadata)}
                        </div>
                    )}
                </div>
            ))
        )}
    </div>
            </div >
        </div >
    );
};

export default CommandCenter;
